#!/usr/bin/python
# -*- coding: utf-8 -*-
#Info para main_database.db
import datetime

actores = [["Jennifer Lawrence", datetime.date(1990,8,15), "Femenino", "images/1.jpg"],
		   ["Leonardo DiCaprio", datetime.date(1974,11,11), "Masculino", "images/2.jpg"],
		   ["Bruce Willis", datetime.date(1955,3,19),"Masculino","images/3.jpg"],
		   ["Joseph Gordon-Levitt", datetime.date(1981,2,17), "Masculino", "images/4.jpg"],
		   ["Ellen Page", datetime.date(1987,2,21), "Femenino", "images/5.jpg"]]

peliculas = [["The Hunger Games", datetime.date(2012,3,23), "Gary Cross", "Katniss Everdeen voluntarily takes her younger sister's place in the Hunger Games, a televised fight to the death in which two teenagers from each of the twelve Districts of Panem are chosen at random to compete."],
		     ["Silver Linings Playbook", datetime.date(2013,1,25), "David O.Russell", "After a stint in a mental institution, former teacher Pat Solitano moves back in with his parents and tries to reconcile with his ex-wife. Things get more challenging when Pat meets Tiffany, a mysterious girl with problems of her own."],
		     ["Inception", datetime.date(2010,8,6), "Christopher Nolan", "A skilled extractor is offered a chance to regain his old life as payment for a task considered to be impossible."],
		     ["Django Unchained", datetime.date(2013,1,18), "Quentin Tarantino", "With the help of a German bounty hunter, a freed slave sets out to rescue his wife from a brutal Mississippi plantation owner."],
		     ["A Good Day to Die Hard", datetime.date(2013,2,15), "John Moore", "John McClane travels to Russia to help out his seemingly wayward son, Jack, only to discover that Jack is a CIA operative working to prevent a nuclear-weapons heist, causing the father and son to team up against underworld forces."]]

relaciones = [[1,1,"Katniss Everdeen","Katniss Everdeen (played by Jennifer Lawrence) is a 16 year old female with straight black hair, olive skin, and brown eyes. Her best friend, Gale (played by Liam Hemsworth), and her love to hunt. The morning before the Reaping, Gale and Katniss are out hunting. They talk about running away, but the idea is quickly distinguished. The Reaping comes sooner than later, and they are all waiting to be called. Katniss's younger sister, Primrose played by Willow Shields), is just turning 12, and so her name is going to go into the Reaping one time. Effie Trinket, (played by Elizabeth Banks) pulls out the female's name. Primrose Everdeen! Prim is freaking out, and so is Katniss. Katniss volunteers as a tribute in place of Prim. Therefore, she is whisked away with the male tribute, Peeta, (played by Josh Hutcherson). Katniss goes through the games, and eventually meets with Peeta and they begin an alliance."],
			  [1,2,"Tiffany","Tiffany is a messed-up twenty-something who's had an unfulfilling childhood, who knows how to lure men, and meeting the oddball from a mental health 'facility' causes her to encourage him, adding to her potential admirers. But he is helpful to her in a different way, and she in turn develops an attachment when he starts by rejecting her as he is already married [though separated]. She does him a favour, against her own inner wishes, then uses this as a lure for him to help her in return: be her partner in a dance competition. With hitches and irritations to both sides of this partnership, each learns to cope in a different way, and the outcome is in doubt right until the end. However, Tiffany both helps and is helped by the relationship: she gets to be less messed-up, and he recovers well from his mental problem."],
			  [2,3,"Cobb","Cobb is an extractor - he enters people's dreams, steals their secrets, and sells them to their competitors. He used to have a legal job involving extraction and dream sharing, but is currently a wanted man and must resort to other means. Cobb is wanted by the government for killing his wife, Mal, on their anniversary. He's innocent, but the government won't believe him. He has two children, James and Phillipa, whom he was forced to leave behind when he went on the run. They now live with their grandmother in the states. Cobb visits their grandfather, who works in Paris, and gives his children gifts through him. Everything Cobb does he does to find a way home to his kids."],
			  [2,4,"Calvin Candie","Calvin Candie is the Francophile owner of Candyland, the fourth largest and most notorious plantation in all Mississippi, who has acquired Django's wife Broomhilda through questionable means."],
			  [3,5,"John McClane","John McClane, Male, Irish-American, born on the 11th of August 1957 New York City, New York, United States. John McClane works as detective lieutenant with the New York City Police Department. He was married to Holly Gennero McClane whom he divorced later and has two Children with, John McClane, Jr. & Lucy McClane"],
			  [4,3,"Arthur", "Arthur is Cobb's right hand man, and apparently closest friend. They have known each other since before the tragic death of Cobb's wife. He lives in America, but travels the world with Cobb. Arthur and Cobb used to work with Eames, but Arthur and Eames appear to dislike each other now. The three never divulge any information about their past experiences together so no further facts can be drawn."],
			  [5,3,"Ariadne", "Ariadne is a student of architecture in France. She meets Cobb through one of her teachers, who is Cobb's father-in-law. After a few tests, she is brought into the team as their official Architect. At first she is adverse to dream sharing but can't stay away from the freedom that comes from it."]]